defaults:
  - models: rollout
  - override hydra/launcher: joblib

input_len: 32
output_len: 1
batch_size: 256
epochs: 1
seed: 0

hydra:
  launcher:
    n_jobs: 4

dataset:
  path: /media/egghead/Scratch/joey/simulation_data/patient_one_data.zarr/
  training_size: 7500000

evaluation:
  path: /media/egghead/Scratch/joey/simulation_data/patient_two_data.zarr/
  evaluation_size: 10

training:
  mode: rollout
  lr: 1e-4
  weight_decay: 1e-2
  rollout_steps: 32

checkpoint:
  save_path: hydra-test.pth
  load: false
  path: hydra-test.pth

compile: true


