defaults:
  - models: rollout
  - override hydra/launcher: joblib

input_len: 32
output_len: 1
batch_size: 128
epochs: 5
seed: 0

hydra:
  launcher:
    n_jobs: 6

dataset:
  path: /home/jdihardjo/simdata/train.zarr/
  training_size: 1500000

evaluation:
  path: /home/jdihardjo/simdata/evaluation.zarr/
  evaluation_size: 50

training:
  mode: rollout
  lr: 2e-4
  weight_decay: 1e-1
  rollout_steps: 16

checkpoint:
  save_path: hydra-test.pth
  load: false
  path: hydra-test.pth

compile: true


